Makefile, README.md, scripts/Makefile.ci
* Clean up Makefile
* Add `check-go` target and dep to provide informative message
* Update README.md to be more explicit about the dependency
=> Explicitly check golang dependency in Makefile.

.travis.yml, scripts/upload_artifacts.sh
this is a step in preparation towards automation around release process
=> uploading artifacts to s3 from windows

pkg/handlers/override.go, pkg/handlers/override_test.go, pkg/handlers/user_overrides.go, pkg/handlers/user_overrides_test.go
* Add override handler
To keep the scope small I'm breaking out the changes in PR #133 into several smaller PRs.
=> Add override handler.

pkg/handlers/track.go, pkg/handlers/track_test.go
* Add track handler
To keep the scope small I'm breaking out the changes in PR #133 into several smaller PRs.
=> Add track handler.

pkg/handlers/optimizely_config.go, pkg/handlers/optimizely_config_test.go
* Add config handler
To keep the scope small I'm breaking out the changes in PR #133 into several smaller PRs.
=> Add config handler.

pkg/handlers/activate.go, pkg/handlers/activate_test.go, pkg/handlers/utils.go, pkg/optimizely/client.go, pkg/optimizely/client_test.go
* Add activate handler
To keep the scope small I'm breaking out the changes in PR #133 into several smaller PRs.
=> Add activate handler.

.travis.yml, CHANGELOG.md, docs/getting-started.md
adds 20s to the build in exchange for url check / spell check all *.md in repo
=> add url check and spell check on markdown files

CHANGELOG.md
- Add support for typed user attributes
- Add event-stream API for notifications
- Add basic client credentials grant flow
- Add native TLS support via configuration
- Refactor to a POST based action API
=> Update CHANGELOG for 0.12.0.

cmd/testdata/default.yaml, config/config.go
- make camel case consistent json/yaml tags
=> feat: make camel case consistent json/yaml tags

README.md, docs/getting-started.md
Adds changes and more clarification to improve the first-time landing experience for people new to Optimizely and new to Agent.
=> docs (readme): Improve landing experience

pkg/server/server.go, pkg/server/server_test.go
- the order of cipher is important, so made it happen...
=> feat: keeping the order for ciphers

api/openapi-spec/openapi.yaml
- adding OAuth functionality in openapi.yaml 
OASIS-6028
=> feat: Update openapi.yaml to describe OAuth functionality

pkg/server/server.go, pkg/server/server_group.go, pkg/server/server_group_test.go, pkg/server/server_test.go
- shut down all listeners on any legit error coming from the server
=> feat: shut down all listeners on bad JWKS init /  bad TLS init

CHANGELOG.md
- Update CHANGELOG.md for v0.13.0 release
=> Update CHANGELOG.md for v0.13.0.

scripts/Makefile.ci
=> Fix docker deploy.

scripts/build.ps1
- Fix silent failure of windows build.
- Check exit status of binary build.
=> Fail the build if the binary cannot be built.

docs/getting-started.md, examples/advanced.py, examples/basic.py, examples/override.py, examples/track.py
- Add userAttributes to examples
- Add eventTags to track example
- Update getting started to use docker
=> Update docs and examples.

CHANGELOG.md
- Update windows build script
- Remove pre-v1 api references
- Allow unknown keys in /activate request
- Improve API token issuer and auth client config
- Expand on example python scripts and general documentation
=> docs(changelog): Update changelog for 0.14.0

README.md, docs/getting-started.md
- Add, update missing config options in README.md
- Simplify example docker run commands
- OASIS-6092
- OASIS-6093
=> docs(readme): Simplify the docs.

pkg/handlers/activate.go
- Adds debug logs for non-existent keys
- OASIS-6094
=> refactor(activate): Add some more logging.

.gitignore, .travis.yml, Makefile, README.md, go.mod, go.sum, pkg/routers/api.go, pkg/routers/api_test.go, scripts/build.ps1, web/static/index.html, web/static/openapi.yaml
- Embeds openapi.yaml into go executable
- Serves openapi.yaml from api router
- Adds basic index handler
=> Serve openapi.yaml statically.

examples/.gitignore, examples/README.md, examples/requirements.txt, examples/track.py
- Add README.md to examples folder
- Add requirements.txt for python dependencies
- Add docstring to track.py
- OASIS-6096
=> docs(examples): Add documentation of python examples.

README.md
Add to README.md to instruct users how to build Agent in Windows.
=> docs(readme): add windows blurb

go.mod, go.sum, pkg/optimizely/cache.go, pkg/optimizely/cache_test.go, pkg/optimizely/logger.go, pkg/optimizely/optimizelytest/client.go
- Add SDK key to logging output
- Bump to recent go-sdk commit
- Fix test to use actual constructor
=> Incorporate new SDK logging fields.

README.md
need to include `make install` due to new deps
=> ci(docs): update README.md

.travis.yml, Makefile, README.md, scripts/dockerfiles/Dockerfile.alpine, scripts/dockerfiles/Dockerfile.static
included dependency on statik for `make run`
=> fix: improved Makefile

.travis.yml, docs/auth.md, scripts/ci_build_generate_secret.sh
build generate_secret in travis so that it can be uploaded to github and be part of the release
=> ci(travis): build generate_secret tool in ci

.travis.yml, scripts/ci_attach_generate_secret.sh, scripts/ci_build_generate_secret.sh
add ability to build for other OS to make available generate_secret to different platforms
=> ci(travis): build generate_secret for windows and macos

README.md, cmd/optimizely/main_test.go, cmd/testdata/default.yaml, config.yaml, config/config.go, config/config_test.go, pkg/optimizely/cache.go
- Added support to pass through DatafileURLTemplate from the Agent config to the Go SDK project config manager.
- FSC should pass.
- Updated unit tests accordingly.
- https://optimizely.atlassian.net/browse/OASIS-6329
=> feat(datafile): Support for DatafileURLTemplate.

scripts/build.ps1
=> ci(travis): meant PATH not the value of it

go.mod, go.sum, pkg/optimizely/client.go
- support json variables in optimizely config
=> feat: make changes to support FJSON

go.mod, go.sum, pkg/server/server_test.go
- Update to the latest go-sdk release
- Release includes official support for OptimizelyJSON variables
- Fix flaky coverage reporting by waiting for full server shutdown
=> Update to go-sdk v1.3.0

README.md, config.yaml
- Update CORS docs in README.md
- OASIS-6584
=> docs(cors): update CORS docs in README.

docs/readme-sync/deploy-as-a-microservice/010 - optimizely-agent.md
=> trivial edit to test readme sync

docs/readme-sync/deploy-as-a-microservice/040 - configure-optimizely-agent/040 - advanced-configuration.md
=> Update 040 - advanced-configuration.md

docs/readme-sync/deploy-as-a-microservice/012 - quickstart.md
=> adding video resource

.travis.yml, docs/readme-sync/deploy-as-a-microservice/012 - quickstart-for-agent.md
=> adding preview stage for readme-sync

.travis.yml, CHANGELOG.md
=> modified travis to include beta release, modifying CHANGELOG to trigger a release

CHANGELOG.md
- preparing agent 2.0.0 release
=> preparing agent 2.0.0 release

pkg/middleware/batch.go, pkg/middleware/batch_test.go, pkg/server/server.go
- adding batching for agent
- it was done in middleware to take advantage of  ServeHTTP
=> feat: adding batching for agent

README.md, cmd/optimizely/main_test.go, cmd/optimizely/testdata/default.yaml, config/config.go, config/config_test.go, pkg/middleware/batch.go, pkg/middleware/batch_test.go, pkg/server/server.go
- making batching requests in parallel
- the order of batching responses is not guaranteed.
=> feat: batching in parallel

CHANGELOG.md
=> prepare 2.1.0 release

config.yaml
- Fix double array in `allowedOrigins`
- Add `*` to `allowedHeaders`
The cors section in config.yaml should illustrate how to enable cors if uncommented.
=> Update example cors in config.yaml.

CHANGELOG.md, go.mod, go.sum, pkg/optimizely/optimizelytest/config.go
=> chore: prepare 2.3.0 release

CHANGELOG.md, go.mod, go.sum
=> chore: prepare agent 2.3.1

api/openapi-spec/openapi.yaml, pkg/handlers/get_datafile.go, pkg/handlers/get_datafile_test.go, pkg/optimizely/optimizelytest/config.go, pkg/routers/api.go, pkg/routers/api_test.go
- Providing datafile access through `/datafile` endpoint
- https://optimizely.atlassian.net/browse/OASIS-5500
=> feat: Adding new /datafile endpoint

CHANGELOG.md, go.mod, go.sum
Changelog for 2.4.0 (decide-api) release
=> chore: prepare 2.4.0 release

.travis.yml, docs/readme-sync/v3.1/deploy-as-a-microservice/012 - quickstart-for-agent.md, docs/readme-sync/v3.1/deploy-as-a-microservice/030 - use-optimizely-agent/010 - evaluate-rest-apis.md, docs/readme-sync/v4.0/deploy-as-a-microservice/012 - quickstart-for-agent.md, docs/readme-sync/v4.0/deploy-as-a-microservice/030 - use-optimizely-agent/010 - evaluate-rest-apis.md
=> docs - fixing broken links

go.mod, go.sum, pkg/handlers/decide.go, pkg/handlers/decide_test.go
- Update `TranslateOptions` to use `go-sdk`.
=> refactor: Remove getDecideOptions to use go-sdk method.

.travis.yml
- For now disabling readme sync, will rely on manual push to readme.
=> fix: disabling readmesync for now

examples/README.md, examples/advanced.py, examples/advanced_activate.py, examples/basic.py, examples/basic_activate.py
- Update code examples and README with decide API
- https://optimizely.atlassian.net/browse/OASIS-7580
Tested new code samples locally
=> [OASIS-7580] Update examples with decide api

.golangci.yml, .travis.yml, pkg/handlers/oauth_test.go, pkg/handlers/webhook_test.go, pkg/jwtauth/jwtauth.go
- Fix and enforce Go fmt. Do not simplify.
- Run lint with fmt on and simplify off.
=> Enforce go fmt in agent.

tests/acceptance/README.md
Add info about the project that the tests run against.
- Add information about the project acceptance tests run against
=> Add info about the project acceptance tests use

CHANGELOG.md
- Update changelog for a new minor release 2.6.0 - forced decisions
- https://optimizely.atlassian.net/browse/OASIS-7947
=> (chore) Prepare for 2.6.0 release

CHANGELOG.md
- Update changelog for a new minor release 2.7.0 - UserProfileService
- https://optimizely.atlassian.net/browse/OASIS-8254
=> (chore) Prepare for 2.7.0 release

CHANGELOG.md
- Update changelog for a new minor release 2.7.1 - Async UserProfileService
=> chore: Prepare for 2.7.1 release

.github/workflows/agent.yml, .github/workflows/integration_test.yml, scripts/ci_build_generate_secret.sh, scripts/dockerfiles/Dockerfile.alpine, scripts/dockerfiles/Dockerfile.static
- We remove travis yaml and moved all the stages to git action.
NOTE: 
Passed build [link](https://github.com/optimizely/agent/actions/runs/3911485715): 
All tests should pass
=> chore: removed travis yml and added git action support

CHANGELOG.md
- Update change-log for a new major release 3.0.0
- https://jira.sso.episerver.net/browse/FSSDK-8911
=> [FSSDK-8911] chore: Prepare for 3.0.0 release

.github/workflows/agent.yml, .travis.yml
- Adding back travis since some jobs were failing on GitAction.
=> fix: Adding back travis.yml

README.md, api/openapi-spec/openapi.yaml, docs/readme-sync/v3.1/deploy-as-a-microservice/010 - optimizely-agent.md, docs/readme-sync/v3.1/deploy-as-a-microservice/012 - quickstart-for-agent.md, docs/readme-sync/v3.1/deploy-as-a-microservice/020 - setup-optimizely-agent.md, docs/readme-sync/v3.1/deploy-as-a-microservice/030 - use-optimizely-agent/010 - evaluate-rest-apis.md, docs/readme-sync/v3.1/deploy-as-a-microservice/030 - use-optimizely-agent/020 - admin-api.md, docs/readme-sync/v3.1/deploy-as-a-microservice/030 - use-optimizely-agent/index.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/010 - authorization.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/020 - webhooks-agent.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/031 - agent-notifications.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/040 - advanced-configuration.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/050 - agent-plugins.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/index.md, docs/readme-sync/v4.0/deploy-as-a-microservice/010 - optimizely-agent.md, docs/readme-sync/v4.0/deploy-as-a-microservice/012 - quickstart-for-agent.md, docs/readme-sync/v4.0/deploy-as-a-microservice/020 - setup-optimizely-agent.md, docs/readme-sync/v4.0/deploy-as-a-microservice/030 - use-optimizely-agent/010 - evaluate-rest-apis.md, docs/readme-sync/v4.0/deploy-as-a-microservice/030 - use-optimizely-agent/020 - admin-api.md, docs/readme-sync/v4.0/deploy-as-a-microservice/030 - use-optimizely-agent/index.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/010 - authorization.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/020 - webhooks-agent.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/031 - agent-notifications.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/040 - advanced-configuration.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/050 - agent-plugins.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/index.md, docs/readme.md, examples/README.md, tests/acceptance/README.md
Change Full Stack to Feature Experimentation
=> [FSSDK-8958] Change Full Stack to Feature Experimentation

README.md, api/openapi-spec/openapi.yaml, docs/readme-sync/v3.1/deploy-as-a-microservice/010 - optimizely-agent.md, docs/readme-sync/v3.1/deploy-as-a-microservice/012 - quickstart-for-agent.md, docs/readme-sync/v3.1/deploy-as-a-microservice/020 - setup-optimizely-agent.md, docs/readme-sync/v3.1/deploy-as-a-microservice/030 - use-optimizely-agent/010 - evaluate-rest-apis.md, docs/readme-sync/v3.1/deploy-as-a-microservice/030 - use-optimizely-agent/020 - admin-api.md, docs/readme-sync/v3.1/deploy-as-a-microservice/030 - use-optimizely-agent/index.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/010 - authorization.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/020 - webhooks-agent.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/031 - agent-notifications.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/040 - advanced-configuration.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/050 - agent-plugins.md, docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/index.md, docs/readme-sync/v4.0/deploy-as-a-microservice/010 - optimizely-agent.md, docs/readme-sync/v4.0/deploy-as-a-microservice/012 - quickstart-for-agent.md, docs/readme-sync/v4.0/deploy-as-a-microservice/020 - setup-optimizely-agent.md, docs/readme-sync/v4.0/deploy-as-a-microservice/030 - use-optimizely-agent/010 - evaluate-rest-apis.md, docs/readme-sync/v4.0/deploy-as-a-microservice/030 - use-optimizely-agent/020 - admin-api.md, docs/readme-sync/v4.0/deploy-as-a-microservice/030 - use-optimizely-agent/index.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/010 - authorization.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/020 - webhooks-agent.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/031 - agent-notifications.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/040 - advanced-configuration.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/050 - agent-plugins.md, docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/index.md, docs/readme.md, examples/README.md, tests/acceptance/README.md
- Change Full Stack to Feature Experimentation
=> [FSSDK-8958] docs: change Full Stack to Feature Experimentation

CHANGELOG.md
=> [FSSDK-8958] chore: prep for 3.0.1 release

.github/workflows/agent.yml
- A env variable was causing issue with make file 
- All tests should pass.
=> [FSSDK-8958] Fix: Moved make file to separate step

CHANGELOG.md
=> [FSSDK-8958] chore: bump release date

.github/workflows/agent.yml, go.mod, go.sum, pkg/handlers/send_odp_event_test.go
- Updates go-sdk version to fix Null and Empty Values in sendOdpEvent.
- All tests should pass.
- [FSSDK-9080](https://jira.sso.episerver.net/browse/FSSDK-9080)
=> [FSSDK-9080]: Updates go-sdk version to fix Null and Empty Values in sendOdpEvent.

pkg/handlers/send_odp_event.go, pkg/handlers/send_odp_event_test.go
- Fixes incorrect parameter passing for send-odp-event.
- Updated unit tests
- [FSSDK-9027](https://jira.sso.episerver.net/browse/FSSDK-9027)
=> [FSSDK-9027]: Fixes issue with parameters for send-odp-event.

plugins/odpcache/services/redis_cache.go
- Fixes odp cache reset for redis.
- All tests should pass.
=> fix(odp-cache): fixes reset issue with redis odp cache.

CHANGELOG.md
- Prepare for 4.0.0-beta release
- [FSSDK-9111](https://jira.sso.episerver.net/browse/FSSDK-9111)
=> [FSSDK-9111] chore: prepare for 4.0.0-beta release

CHANGELOG.md
=> bump release date

api/openapi-spec/openapi.yaml
- Nit fixes for openapi
- [FSSDK-9576](https://jira.sso.episerver.net/browse/FSSDK-9576.)
=> [FSSDK-9576]: nit fixes for openapi.

CHANGELOG.md
=> chore: prepare for 3.1.0 release
