optimizely/agent

- Makefile
- go.mod
- go.sum
* Set's the ClientName and Version as part of the build
Client name and version are included in the log requests to Optimizely to track adoption. We want to be able to distinguish Agent requests from native go-sdk requests.
> Add Agent version and name.

- Makefile
- README.md
- go.mod
- go.sum
- scripts/dockerfiles/Dockerfile.alpine
- scripts/dockerfiles/Dockerfile.static
* Update to latest go-sdk master to fix /features and /experiments responses
* Moved "Running Optimizely via Docker" after "... via Source"
* Add more content to README.md.
* Document Golang 1.13+ dependency
* Update docker files to pull from /agent
Several smallish enhancements I felt easier to roll into a single commit. The documentation is still highly geared towards operations and developing Agent. The descriptions of the Full Stack API is pretty limited providing just the basic concepts as we'll defer to generated API docs and the developer site for more Agent consumer content.
> Clean up docs and pull latest go-sdk.

- CHANGELOG.md
* Update CHANGELOG for 0.11.0
Prepare for release.
> Update CHANGELOG for 0.11.0.

- api/openapi-spec/openapi.yaml
- pkg/handlers/interface.go
- pkg/handlers/user.go
- pkg/handlers/user_overrides.go
- pkg/handlers/user_overrides_test.go
- pkg/handlers/user_test.go
- pkg/routers/api.go
- pkg/routers/api_test.go
* Moves user overrides into into own file and test file.
* Updates the method signture to use a request body as opposed to a URL param
After some discussion with @mjc1283 we decided to refactor the overrides API. This makes the API explicitly disjoint from the typical API usage by namespacing it under `/overrides`. We also changed the method signature to better reflect that only a single override can exist for a given experiment/user combo.
> Refactor overrides into it's own API set

- pkg/middleware/cached.go
- pkg/middleware/cached_test.go
- pkg/middleware/utils.go
- pkg/middleware/utils_test.go
* Coerce user attributes to support data types
* Update tests to match coerced values
This change fixes a compatibility gap where all user attribute values were being handled as strings. Values are now coerced into typed values when applicable. Note that this will require some documentation on how values are coerced since this is unique to Agent.
Note that strings can be forced if quoted in the URL params.
> Add type coercion to user attributes. 

- README.md
- cmd/main.go
- cmd/main_test.go
- cmd/testdata/default.yaml
- config.yaml
- config/config.go
- config/config_test.go
- pkg/handlers/admin_entities.go
- pkg/handlers/admin_entities_test.go
- pkg/optimizely/cache.go
- pkg/optimizely/cache_test.go
- pkg/routers/admin.go
* Move Author, Name and Version to root config
* Move SDKKeys and Processor to root config
* Add uptime to /info because it seamed like a good idea
* Add admin /config route to support operations and validate config
* Updates README.md and config.yaml
Exposing "optly" in the configs was gross. Moving items to the root of the application config felt more appropriate in some cases as Agent _is_ optimizely. I also wanted to expose the configuration in the routes as this is a handy endpoint when you want to confirm that certain configs are loaded etc.
> Refactor configuration struct and add /config endpoint.

- go.mod
- go.sum
- pkg/handlers/feature.go
- pkg/handlers/user.go
- pkg/handlers/user_test.go
- pkg/optimizely/client.go
- pkg/optimizely/optimizelytest/processor.go
* Use the latest master where GetAllFeatureVariables returns a `map[string]interface{}`
* Updates to the latest `ProjectConfig` interface
Note that the original ticket called for an override mechanism via service config and a URL parameter. That implementation will be dependent on the current [RFP](https://github.com/optimizely/agent/pull/133), so we should wait until that change is merged before adding that capability.
> Support the latest master SDK version.

- pkg/middleware/cached_test.go
- pkg/middleware/utils.go
* Treat empty query params as nil
* Empty strings can be passed as `key=""`
Currently empty query values are treated as strings which fails the compatibility suite use cases.
> Add nil query param support.

- pkg/middleware/auth.go
- pkg/middleware/auth_test.go
- pkg/routers/admin.go
- pkg/routers/api.go
- pkg/routers/api_test.go
- adding Authorize middleware for accepting a token when auth is enabled 
- for now enabled/disabled auth is determined by the presence of auth object in config file
> feat: token acceptor for admin and api

- pkg/handlers/user.go
- pkg/handlers/user_test.go
* Customer of the legacy API endpoints expect string variables
* New /v1 returns typed-variables, this still needs to be made configurable (future PR)
> Revert to str for legacy api.

- cmd/main_test.go
- cmd/testdata/default.yaml
- config/config.go
- config/config_test.go
- pkg/server/server.go
- pkg/server/server_test.go
- add a configurable blacklist for ciphers
- the implementation removes the cipher from our default config if that cipher is blacklisted
- blacklist is provided in configuration as a list of cipher hexadecimal values
> feat: Add blacklist for crypto cyphers

- cmd/main_test.go
- cmd/testdata/default.yaml
- config/config.go
- config/config_test.go
- pkg/handlers/notification_disabled.go
- pkg/handlers/notification_disabled_test.go
- pkg/handlers/user_overrides_disabled.go
- pkg/handlers/user_overrides_disabled_test.go
- pkg/routers/api.go
- pkg/routers/api_v1.go
- pkg/routers/api_v1_test.go
- disable /notifications and /overrides by default
- allow them to be enabled via configuration
> feat: Disable /notifications and /overrides by default

- api/openapi-spec/openapi.yaml
* Fix spec to use singular type enum
The implementation differed from the documented spec. Singular is more semantic since it matches the `type` attribute in the response entities.
> Fix spec to use singular enums.

- api/openapi-spec/openapi.yaml
* Add 400 - Bad Request to API spec
`eventKey` is a required parameter when calling `/track`. Omitting the value or key should return a 400. This is distinct from a 404 response which indicates that a key was supplied, but it does not exist as part of the project.
> Add /track 400 response to the spec.

- api/openapi-spec/openapi.yaml
- pkg/handlers/activate.go
- pkg/handlers/activate_test.go
- pkg/optimizely/client.go
- pkg/optimizely/client_test.go
* Return error if `?type=` parameter is not supported
Current behavior is to ignore the unknown type filter.
> Handle invalid filter types.

- README.md
- cmd/main.go
- cmd/main_test.go
- cmd/testdata/default.yaml
- config.yaml
- config/config.go
- config/config_test.go
- pkg/optimizely/cache.go
- pkg/optimizely/cache_test.go
* Rename `processor` config to `client` config
* Add `client.pollingInterval` as a configurable attribute
* Add unit test for `client` config in `main_test.go`
* Add missing config examples in default `config.yaml`
* Fix up examples to match standard casing in config.go
* Update README.md where appropriate
Refactoring all "sdk client" config into a single namespace for clarity and tighten up docs and examples along the way.
> Refactor and document client config.

- pkg/routers/api.go
- pkg/routers/api_v1.go
- pkg/routers/api_v1_test.go
This makes the existing OAuth functionality available in the V1 API service:
- Exposed token issuer endpoint at `POST /v1/oauth/token`
- Connected token authorization middleware to `v1/config`, `v1/activate`, `v1/track`, and `v1/override`
- Manually tested
- Updated V1 router unit tests
- Existing tests for old API and Admin services should pass
https://optimizely.atlassian.net/browse/OASIS-6028
> feat: Connect access token creation handler and auth middleware in V1 API

- pkg/handlers/track.go
- pkg/handlers/track_test.go
- pkg/optimizely/client.go
- pkg/optimizely/client_test.go
- pkg/optimizely/interface.go
* Create `SycnedConfigManager` interface for OptlyClient
* Check the OptlyClient config manager for event key prior to calling track
This is a bit of a workaround since the native SDK swallows tracking errors related to event key existence and events are not part of the `OptimizelyConfig` object. We could have opened up the SDK a bit, but that would have amounted to a breaking change if we started to propagate errors (which is arguably the right approach). That being said, for track in particular I want to set us up to remove the event creation constraint within the application in which case we'd simply remove this code as 404 will no longer be applicable.
> Throw 404 if eventKey not part of the project

- README.md
- cmd/main_test.go
- cmd/testdata/default.yaml
- config/config.go
- config/config_test.go
- docs/auth.md
- examples/auth.py
- pkg/handlers/oauth.go
- pkg/handlers/oauth_test.go
- pkg/middleware/auth.go
- pkg/middleware/auth_test.go
This provides documentation regarding authorization and TLS functionality recently added. This includes updates to the config properties table, an authorization guide under `/docs` , and a python example under `/examples`.
Also included are fixes for small issues uncovered while creating the documentation:
- Added support for multiple HMAC validation secrets, to facilitate zero-downtime rotation. The first secret in the array will be used to sign issued tokens
- Fix for an invalid response code (`0`) when the token issuer endpoint received invalid JSON in the request body
https://optimizely.atlassian.net/browse/OASIS-5899
> fix: Add documentation for auth & TLS functionality, plus related fixes

- pkg/handlers/oauth.go
- pkg/handlers/oauth_test.go
- pkg/routers/admin.go
- pkg/routers/api.go
- pkg/routers/api_v1.go
- pkg/routers/api_v1_test.go
Fix the following bug in the access token issuer endpoint: 
- Valid client credentials are set in configuration
- Agent config lacks an hmac secret or was configured with an empty hmac secret
Expected:
- Server does not start with invalid configuration
Actual:
- Server starts and issues access tokens with invalid config
With this change, the server does not start, and errors are logged
> fix: Don't start with invalid auth configuration (missing hmac secret)

- api/openapi-spec/openapi.yaml
- pkg/handlers/activate.go
- pkg/handlers/activate_test.go
- pkg/optimizely/client.go
- pkg/server/server_test.go
This PR changes how the /activate endpoint handles experiment and feature keys that can't be found in the datafile. Instead of returning a 'key not found' message, it will return info detailing what specific key wasn't able to be found, while also returning info about the experiments that _were_ found.
**They "why"**
The /activate endpoint currently allows multiple experiment and feature keys to be passed up as params. However, if _any_ of those keys cannot be found in the current datafile an error is returned, even if some of the keys were able to be found.
It is very common that a code base includes code for some experiments that are turned on, and some that aren't, but if an app that uses this service wants to batch its calls together for performance and efficiency, then this makes it …
> /activate endpoint leniency

- api/openapi-spec/openapi.yaml
- cmd/optimizely/main_test.go
- cmd/testdata/default.yaml
- config.yaml
- config/config.go
- docs/auth.md
- examples/auth.py
- pkg/handlers/oauth.go
- pkg/handlers/oauth_test.go
- pkg/jwtauth/jwtauth.go
- pkg/jwtauth/jwtauth_test.go
- pkg/middleware/auth.go
- pkg/middleware/auth_test.go
- pkg/routers/api.go
- pkg/routers/api_test.go
`X-Optimziely-Sdk-Key` header is no longer required by token issuer endpoint. Instead, SDK keys are given in configuration of clients. 1 or more SDK keys are required for each client.
https://optimizely.atlassian.net/browse/OASIS-6073
> fix: In API access token issuer, use SDK keys from configuration, not request header

- docs/auth.md
- pkg/handlers/oauth.go
- pkg/handlers/oauth_test.go
- pkg/jwtauth/jwtauth.go
- pkg/middleware/auth.go
- pkg/middleware/auth_test.go
Introduce an expectation that `hmacSecrets` config values are in base64 format. The rationale is that we already have this expectation for client secret hashes in config, and we should be consistent with how we interpret and convert config strings into byte slices.
Manual testing, updated unit tests, updated example and auth guide
> fix(auth): HMAC secret strings from config are interpreted as base64

- api/openapi-spec/openapi.yaml
- pkg/handlers/override.go
- pkg/handlers/override_test.go
- pkg/optimizely/client.go
- pkg/optimizely/client_test.go
- pkg/optimizely/optimizelytest/client.go
- pkg/optimizely/optimizelytest/config.go
- Introduces a response body to the /override endpoint
- Add additional helper method to optimizelytest pkg
It's been being apparent that Agent should be serving more meaningful context in it's responses than the standard HTTP codes can provide. This PR adds a response body to the /override endpoint to reflect back meaningful sideeffect to the user. 
Note: This is an alternative to https://github.com/optimizely/agent/pull/179 which responds with HTTP error codes.
> feat(override): adds override response body

- pkg/handlers/track_test.go
- pkg/optimizely/cache.go
- pkg/optimizely/cache_test.go
- pkg/optimizely/client_test.go
- pkg/optimizely/interface.go
- Fix omission of passing flushInterval config
- Refactor to facilitate testing
- OASIS-6097
> fix(cache): Adds flushInterval to client loader

- scripts/build.ps1
for windows users, in case they want to use their already installed versions of golang or git instead of the hardcoded ones in the script
> fix(ci): allow skipping installation of prereqs

- tests/acceptance/test_acceptance/conftest.py
@mikecdavis Added a conditional to allow remote host to run tests.
Before it wasn't quite working.
That will help JC with deployed Agent.
> fix: enabled tests to run on remote server

- README.md
- docs/advanced-configuration.md
Add advanced configuration notes in the docs directory. Mentions config option precedence, Viper, the syntax for setting environment variables for nested config options, and options that can't be set via environment variable
https://optimizely.atlassian.net/browse/OASIS-6095
> docs: Add advanced configuration notes in docs

- .travis.yml
- scripts/dockerfiles/Dockerfile.alpine
- scripts/dockerfiles/Dockerfile.static
- due to new statik depedency, added extra line to run `make install` to the build Dockerfiles
- made uploading packages contingent on successful package creation (previously it was uploading regardless)
> ci(travis): include statik dependency

- api/openapi-spec/openapi.yaml
- pkg/handlers/activate.go
- pkg/handlers/activate_test.go
- pkg/handlers/track.go
- pkg/handlers/track_test.go
- pkg/optimizely/client.go
- pkg/optimizely/client_test.go
- tests/acceptance/test_acceptance/test_activate.py
- tests/acceptance/test_acceptance/test_overrides.py
- tests/acceptance/test_acceptance/test_track.py
- Add /track response
- Remove /track 404 in favor of 200 with error body
- Add userId to /activate response
- Update acceptance suite tests
> feat(response): Add more meaningful responses to track and activate

- Makefile
- Use full path to go binaries
Some users might not have `$GOPATH/bin` in their path, this eliminates that assumption.
> chore(Makefile): Use fully qualified path to go deps.

- .travis.yml
Removed pytest argument so test output doesn't include the confusing server logs with red colored text
@mikecdavis .
> fix: made pytest output simpler, no error messages

- pkg/handlers/activate.go
- pkg/handlers/activate_test.go
- Empty userIds should reject the request
Prior to this change, empty userIds would still yield a valid decision which might have masked a request error. If this becomes an sticking point with customers we will introduce a "generateUserId" config option that will allow users to control this behavior. https://optimizely.atlassian.net/browse/OASIS-6132
> fix(activate): Reject empty userId with a 400

- CHANGELOG.md
- Update documentation and examples
- Add response body for override and track
- Add userId in /activate response
- Require userId in /activate request
- Add python integration test suite
- Add route handler and serve /openapi.yaml
- Improve logging from the SDK
> chore(changelog): Prepare CHANGELOG for 1.0.0 release

- scripts/dockerfiles/Dockerfile.alpine
the depdency golangci/golangci-lint requires curl to download
we must provide curl in the base image when compiling agent
> fix: need curl to download golangci/golangci-lint

- docs/auth.md
- Environment variables in documentation do not match the actual variable names used in the agent. This should fix it.
> Fix environment variable's names in auth.md

- scripts/dockerfiles/Dockerfile.alpine
update ca-certificate for alpine image since old one is no longer available
> ci(travis): update ca-certificate in docker alpine

- CHANGELOG.md
- go.mod
- go.sum
- This fixes an error where the batch event processor was creating a http dispatcher without a logger.  This in turn caused a crash.
> fix: update to go-sdk 1.1.3.

- scripts/upload_artifacts.sh
`choco install awscli` previously installed it in `/c/Program Files/Amazon/AWSCLI/bin`
now the same command installs `AWSCLIV2` which drops the aws.exe into `/c/Program Files/Amazon/AWSCLIV2` instead. Only figured this out by doing `ls` in each installed directory. Even these logs didn't help too much: (click detals) https://chocolatey.org/packages/awscli#testingResults
> ci(travis): awscliv2 changed binary location

- .travis.yml
- ~updates the automation so that the release process requires manual "publish"~
- publishes github release once all tests pass
- add slack notification once successfully verified gh release assets (will also slack failures)
- renamed stages to reflect actual purpose
- parallelized some stages where possible to speed up build
> ci(travis): gate github releases for manual publish

- cmd/generate_secret/main.go
- docs/auth.md
- examples/auth.py
Update documentation and secret generation tool output to make it clearer that the values generated can be used for the `hmacSecrets` config option (in addition to the client secret & secret hash configuration options).
> docs: Secret generation tool can be used for hmacSecrets

- CHANGELOG.md
- go.mod
- go.sum
- pkg/optimizely/client.go
- Update Go SDK dependency to v1.2.0 (add support for multi-rule rollouts)
- Revert usage of method not available in Go SDK v.1.2.0
- Update CHANGELOG to prepare for v1.1.0 Agent release
> chore: Update Go SDK to v1.2.0, prepare changelog for release

- api/openapi-spec/openapi.yaml
The current API spec is out of date with the existing implementation. `/track` returns an HTTP 200 and not a 204. The change was made as part of [this](https://github.com/optimizely/agent/commit/70300ade293bfb25286fb8f619fb656274b8f4bc#diff-792ff1ebb42545c5d3e4b34233906b27L75-R70) commit, but the spec was not updated.
> docs(openapi): Fix documented response code

- api/openapi-spec/openapi.yaml
- Fix typo in OptimizelyConfig API spec
> docs(openapi): Fix typo in config spec.

- cmd/optimizely/main.go
- config/config.go
- config/config_test.go
With this change, on startup, when HTTPS or authorization for admin/API endpoints are not set via configuration, warning messages are logged. The messages recommend enabling HTTPS and authorization for production deployments.
OASIS-6585
> feat: Log warnings when HTTPS and authorization are not enabled via configuration

- config/config.go
Fix typos in HTTPS warning message, and comment
OASIS-6585
> fix: Typos in HTTPS disabled warning message

- scripts/dockerfiles/Dockerfile.alpine
- scripts/dockerfiles/Dockerfile.static
- run docker container as non root user
- tested just locally, it needs to be tested while deployed
- travis  handled this new user with no problem:
```
Step 11/13 : COPY --from=builder /etc/passwd /etc/passwd
---> e8bb295c9edf
Step 12/13 : USER agentuser
---> Running in 1035f68bb9ee
Removing intermediate container 1035f68bb9ee
---> 0ebd05595170
Step 13/13 : CMD ["/optimizely"]
---> Running in b140d42bd211
Removing intermediate container b140d42bd211
---> 2c13863c1264
[Warning] One or more build-args [NUM_RUNS SDK_BRANCH TESTAPP_BRANCH TRAVIS_COM_TOKEN] were not consumed
Successfully built 2c13863c1264
Successfully tagged agent-testapp:latest
```
- https://optimizely.atlassian.net/browse/OASIS-6579
> feat: run docker container as non root user

- CHANGELOG.md
- Upgrade to use go-sdk v1.3.0. This adds support for JSON feature variables
- Add /debug/pprof endpoints to the admin service
- Run docker container as non root user
- Log warnings when HTTPS and authorization are not enabled via configuration
> chore(release): Update CHANGELOG for 1.3.0 release.

- README.md
- cmd/optimizely/main_test.go
- cmd/optimizely/testdata/default.yaml
- config.yaml
- config/config.go
- config/config_test.go
- pkg/middleware/cached.go
- pkg/middleware/cached_test.go
- pkg/middleware/utils_test.go
- pkg/optimizely/cache.go
- pkg/optimizely/cache_test.go
- tests/acceptance/test_acceptance/conftest.py
- Add validation parameter for SDK Key header `sdkKeyRegex` to client config
- Update cache loader to validate SDK Key before initializing the Optimizely client
This change allows the SDK Key found in the request header to be validated prior to making the templated URL fetch.
- OASIS-6583
> feat(security): add SDK key validation configuration

- .travis.yml
- README.md
- Replaced codecove.io to coveralls.
- All UT and FSC must pass
- Check should be available for coveralls.
> ci: Added coveralls

- docs/readme-sync/deploy-as-a-microservice/012 - quickstart-with-docker.md
- docs/readme-sync/deploy-as-a-microservice/040 - configure-optimizely-agent/031 - agent-notifications.md
- docs/readme-sync/deploy-as-a-microservice/040 - configure-optimizely-agent/040 - advanced-configuration.md
> fixing whitespaces in markdown

- docs/readme-sync/deploy-as-a-microservice/040 - configure-optimizely-agent/031 - agent-notifications.md
- docs/readme-sync/deploy-as-a-microservice/040 - configure-optimizely-agent/040 - advanced-configuration.md
Readme seems to inconsistently confuse code comments in code blocks (#) with heading markings (#). 
> remove code type in samples = proper code formatting?

- .travis.yml
- docs/internal docs authoring notes.md
- docs for how to use readme-sync
> Create internal docs authoring notes.md

- api/openapi-spec/openapi.yaml
- tests/acceptance/helpers.py
- tests/acceptance/requirements.txt
- tests/acceptance/test_acceptance/conftest.py
- tests/acceptance/test_acceptance/test_activate.py
- tests/acceptance/test_acceptance/test_config.py
- tests/acceptance/test_acceptance/test_overrides.py
- tests/acceptance/test_acceptance/test_track.py
This adds open API request and response validation in acceptance tests. 
Modified acceptance tests which are covering most of the scenarios and used openapi spec to validate that. All must pass.
OASIS-6781
> test: Add open api validation in acceptance tests

- .travis.yml
added a stage to publish beta versions as draft for testing
> added beta stage

- go.mod
- go.sum
- coreos/etc  was vulnerable and  dependency link is changed. Replaced with that link.
OASIS-6869
> fix: Removed vulnerable version coreos/etcd

- api/openapi-spec/openapi.yaml
> 1st stab at API reference for batch

- api/openapi-spec/openapi.yaml
> adding more descriptions

- CHANGELOG.md
- go.mod
- go.sum
- pkg/optimizely/optimizelytest/config.go
- Update to the latest version of go sdk with version, >=, and <= for numbers support as well as datafile accessor (not yet exposed in agent) and match registry.
> chore: update go sdk to 1.4.0 and add stub for GetDatafile in TestProjectConfig

- .travis.yml
- tests/acceptance/test_acceptance/conftest.py
- tests/acceptance/test_acceptance/test_activate.py
- tests/acceptance/test_acceptance/test_batch.py
- tests/acceptance/test_acceptance/test_config.py
- tests/acceptance/test_acceptance/test_overrides.py
- tests/acceptance/test_acceptance/test_track.py
- previously acceptance tests called Agent twice because one test needed a separate instance.
Now that's fixed. All tests run only with one call to Agent. It was nan issue with properly setting environmental variable for operations limit (OPTIMIZELY_SERVER_BATCHREQUESTS_OPERATIONSLIMIT)
- Jira [OASIS-7204](https://optimizely.atlassian.net/browse/OASIS-7204)
> fix: refactored to only one call to acceptance tests in travis.yaml

- README.md
Add additional environment variables `OPTIMIZELY_SERVER_HOST` and `OPTIMIZELY_SERVER_ALLOWEDHOSTS`, needed to allow the container to respond to requests. Also adds `OPTIMIZELY_LOG_PRETTY` for more readable log output.
> docs: Fix docker run command

- .travis.yml
- docs/readme-sync/v4.0/deploy-as-a-microservice/030 - use-optimizely-agent/index.md
docs - trivial wording update for better grammar
> docs - trivial wording update for better grammar

- README.md
Per found issue with a customer
- Core issue: readme and dev docs out of sync with the code
- property name and environmental variable name in configuration file were incorrect. They were missing the "server" keyword. 
Issue reported by SA Simone when working with a customer trying to run agent with custom keyfile and TLS certificate. Agent wouldn't run because incorrect ENV var names were used in the command to run agent.
- https://optimizely.atlassian.net/browse/OASIS-7856
> [OASIS-7856] Update certfile and keyfile property and env var name in README

- README.md
- Alphabetize the configuration list of properties and ENV var names in REadme.
- fix typo in one ENV var
- https://optimizely.atlassian.net/browse/OASIS-7856
> [OASIS-7856] fix: alphabetize and fix typo

- CHANGELOG.md
- Updated changelog, prepare for 2.5.0 release
- OASIS-7920 https://optimizely.atlassian.net/browse/OASIS-7920
> Chore: prepare for 2.5.0 release

- api/openapi-spec/openapi.yaml
- go.mod
- pkg/handlers/decide.go
- pkg/handlers/decide_test.go
- pkg/optimizely/optimizelytest/client.go
- pkg/optimizely/optimizelytest/config.go
Added SetForcedDecision support in decide api.
- unit tests for the new APIs
- FSC tests with new test cases
> feat(ForcedDecisions): adding SetForcedDecision support in decide api.

- go.mod
- go.sum
- Update to the latest version of go sdk 1.8.0
> chore: Updating go-sdk to 1.8.0.

- scripts/ci_upload_packages.sh
- The docker cli default is no longer to push all tagged images
- Adding the -a option per https://docs.docker.com/engine/reference/commandline/push/
- Fixes Travis CI build https://app.travis-ci.com/github/optimizely/agent/builds/244793203
- Jira: https://optimizely.atlassian.net/browse/SRE-2133
> add -a switch to push all tags per https://github.com/docker/cli/pull/2220

- cmd/optimizely/main.go
- cmd/optimizely/main_test.go
- cmd/optimizely/testdata/default.yaml
- config.yaml
- config/config.go
- pkg/middleware/utils.go
- pkg/middleware/utils_test.go
- pkg/optimizely/cache.go
- pkg/optimizely/logger.go
- pkg/optimizely/logger_test.go
- `sdkKey` can be removed from logs by setting `log.includeSdkKey` configuration property to `false`.
> feat(allowed hosts): Added support to remove sdkKey from logs.

- README.md
- docs/readme-sync/v3.1/deploy-as-a-microservice/040 - configure-optimizely-agent/index.md
- docs/readme-sync/v4.0/deploy-as-a-microservice/040 - configure-optimizely-agent/index.md
- plugins/userprofileservice/README.md
- Updating description for OPTIMIZELY_SDKKEYS env variable to only contain `Comma separated sdkKeys`.
- Added documentation for clarity on how to use UPS in a clustered environment.
> Updating documentation for OPTIMIZELY_SDKKEYS env variable and UserProfileService.

- cmd/optimizely/main_test.go
- cmd/optimizely/testdata/default.yaml
- config.yaml
- plugins/userprofileservice/README.md
- plugins/userprofileservice/services/rest_ups.go
- plugins/userprofileservice/services/rest_ups_test.go
- This adds support for asynchronous `Save` using `rest` UPS by setting `async` boolean value inside `config.yaml`.
```
userProfileService:
default: "rest"
services:
rest: 
async: true
```
- Added new unit tests.
- All previous tests should pass.
> refact(ups): Add support for async save call using rest UPS.

- pkg/handlers/oauth.go
- pkg/handlers/oauth_test.go
- pkg/routers/admin.go
- pkg/routers/admin_test.go
- pkg/routers/api.go
- Fixes an issue with `/oauth/token` api which restricted client access. The outer middleware only allowed `application/json`  whereas internally it was again checking again for `application/x-www-form-urlencoded`.
- https://github.com/optimizely/agent/issues/345
> fix(issue#345):  Fixes an issue with oauth/token API denying client access.

- .github/workflows/agent.yml
- Fixed tags push doesn't work with regex.
> fix: tags push doesn't work with regex

- .github/workflows/agent.yml
- README.md
Change build status badge to git actions instead of travis.
> [FSSDK-8958] fix: change build status to actions

- .github/workflows/agent.yml
- Make release check jobs reliant on release creation job
> [FSSDK-8958] ci: make release check wait for release

- .github/workflows/agent.yml
- scripts/ci_attach_generate_secret.sh
- Changed travis tag to release tag and providing it in env
- Removed sending message to slack as it is no longer used by opti
> [FSSDK-8958] ci: Changed travis tag to release tag and providing it in env

- pkg/optimizely/cache.go
- tests/acceptance/helpers.py
- tests/acceptance/test_acceptance/conftest.py
- tests/acceptance/test_acceptance/test_odp_decide.py
- tests/acceptance/test_acceptance/test_send_odp_event.py
- Adds acceptance tests or send-odp-event api.
- Fixes a crash caused by nil logger being passed with odp components.
- [FSSDK-8839](https://jira.sso.episerver.net/browse/FSSDK-8839)
- All tests should pass
> [FSSDK-8839]: Added acceptance tests for send-odp-event.

- .github/workflows/agent.yml
- Replace deprecated set-output command with GITHUB_OUTPUT. Details: [Ref](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- [FSSDK-9003](https://jira.sso.episerver.net/browse/FSSDK-9003)
> [FSSDK-9003] fix(github-actions): Replace deprecated set-output command with GITHUB_OUTPUT

- .github/workflows/agent.yml
- pkg/routers/api.go
- There is an unreachable forced [import](https://github.com/optimizely/agent/blob/master/pkg/routers/api.go#L31) which causes failure in github action in sourceclear part. For this sourceclear failed to list dependencies using `go list -deps -json all` command.
- The local statik package is ignored in the .gitignore & only available after build. Without building the project `go mod tidy` command couldn't find the local statik package.
> fix(github-actions): fix sourceclear github actions failure

- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/ENHANCEMENT.yml
- .github/ISSUE_TEMPLATE/FEATURE-REQUEST.md
- .github/ISSUE_TEMPLATE/config.yml
- Add advanced github issue template
- [FSSDK-9557](https://jira.sso.episerver.net/browse/FSSDK-9557)
> [FSSDK-9557] chore: add github issue template

- pkg/middleware/trace.go
- tests/acceptance/test_acceptance/test_odp_redis.py
- use http response writer from chi router to avoid error case like notification api expects this writer to implement flusher interface. Using http response writer from chi router eliminate any such errors.
- fixed one continuously failing acceptance test
> fix: fix trace middleware http writer

- cmd/optimizely/main.go
- config.yaml
- config/config.go
- pkg/middleware/trace.go
- pkg/middleware/trace_test.go
- pkg/routers/api.go
- pkg/routers/api_test.go
- fix context propagation in distributed tracing
- `traceparent` header is used to get tracing context
> fix: fix context propagation in distributed tracing

- CHANGELOG.md
- updated changelog for release 3.2.0
- [FSSDK-9840](https://jira.sso.episerver.net/browse/FSSDK-9840)
> [FSSDK-9840] chore: prepare for 3.2.0 release

- README.md
- updated readme with webhook & notification synchronization doc
N.B. The official documentation will be updated with the same content once the PR is approved.
- [FSSDK-9973](https://jira.sso.episerver.net/browse/FSSDK-9973)
> [FSSDK-9973] doc: update readme with webhook & notification synchronization doc

- config.yaml
- tests/acceptance/datafile.py
- tests/acceptance/odp_datafile.py
- tests/acceptance/test_acceptance/test_activate.py
- tests/acceptance/test_acceptance/test_batch.py
- tests/acceptance/test_acceptance/test_config.py
- tests/acceptance/test_acceptance/test_decide.py
- Fixed failing acceptance tests
- [FSSDK-10580](https://jira.sso.episerver.net/browse/FSSDK-10580)
> [FSSDK-10580] fix acceptance tests

- pkg/handlers/decide.go
- pkg/handlers/decide_test.go
- tests/acceptance/test_acceptance/test_decide.py
- tests/acceptance/test_acceptance/test_odp_decide.py
- tests/acceptance/test_acceptance/test_odp_redis.py
- tests/acceptance/test_acceptance/test_ups.py
- added IsEveryoneElseVariation marker in decide API
- [FSSDK-10553](https://jira.sso.episerver.net/browse/FSSDK-10553)
> [FSSDK-10553] add IsEveryoneElseVariation marker in decide API

- CHANGELOG.md
- prepared for release v4.1.0
- [FSSDK-10611](https://jira.sso.episerver.net/browse/FSSDK-10611)
> [FSSDK-10611] chore: prepare for release-4.1.0

- config.yaml
- config/config.go
- config/config_test.go
- pkg/optimizely/cache_test.go
- updated config.yaml
- updated regex to allow `=` character
- [FSSDK-10734](https://jira.sso.episerver.net/browse/FSSDK-10734)
> [FSSDK-10734] update regex to allow `=` character

- config.yaml
- config/config.go
- config/config_test.go
- pkg/optimizely/cache_test.go
- tests/acceptance/test_acceptance/conftest.py
- add support for base64 char for SDK Key & access token
- [FSSDK-10734](https://jira.sso.episerver.net/browse/FSSDK-10734)
> [FSSDK-10734] update regex to support base64 char for SDK Key & access token

- .github/workflows/agent.yml
- .golangci.yml
- Makefile
- README.md
- examples/basic.py
- examples/requirements.txt
- go.mod
- scripts/build.ps1
- scripts/dockerfiles/Dockerfile.alpine
- 
- [FSSDK-11338](https://jira.sso.episerver.net/browse/FSSDK-11338)
> [FSSDK-11338] Resolve critical SCA prisma alerts

- pkg/handlers/notification_test.go
- Make agent work with added experimentID and variationID to decision notification listener
- that logic has already been implemented in go-sdk nd it propagates to agent
- no logic changes needed to agent, experimentID and variationID are passing to agent, I just added unit test to very the two  
https://jira.sso.episerver.net/browse/FSSDK-11452
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> [FSSDK-11452] Agent - netspring integration - experimentID, VariationID
